version: '3.8'

services:
  aivlingual-nlp:
    build:
      context: .
      dockerfile: Dockerfile.nlp
    container_name: aivlingual_nlp
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    container_name: aivlingual_redis
    ports:
      - "6379:6379"
    restart: unless-stopped